apiVersion: v1
kind: Service
metadata:
  name: baseline-backend
spec:
  selector:
    app: baseline-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: baseline-client
spec:
  selector:
    app: baseline-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
